export  const BANK_LIST="BANK_LIST";
export  const BRANCH_LIST="BRANCH_LIST";
export  const DRAWEE_BRANCH_LIST="DRAWEE_BRANCH_LIST";
export  const VEIW_BANK_DETAIL="VEIW_BANK_DETAIL";
export  const VEIW_BRANCH_DETAIL="VEIW_BRANCH_DETAIL";
export  const VEIW_DRAWEE_DETAIL="VEIW_DRAWEE_DETAIL";
export  const VEIW_DETAIL="VEIW_DETAIL";

export const SHOW_NOTIFICATION=400;
export const HIDE_NOTIFICATION=3000;