const styles = ({
  style: { tooltip: tooltipStyle = {}, content: contentStyle = {}, arrow: arrowStyle = {} } = {},
}) => ({
  root: {
    position: "absolute",
    zIndex: "1070",
    display: "block",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: "normal",
    lineBreak: "auto",
    lineHeight: "1.42857143",
    textAlign: "start",
    textDecoration: "none",
    textShadow: "none",
    textTransform: "none",
    whiteSpace: "normal",
    wordBreak: "normal",
    wordSpacing: "normal",
    wordWrap: "normal",
    fontSize: 15,
    ...tooltipStyle,
  },
  top: {
    marginTop: -3,
    padding: "5px 0",
  },
  right: {
    marginLeft: 3,
    padding: "0 5px",
  },
  bottom: {
    marginTop: 3,
    padding: "5px 0",
  },
  left: {
    marginLeft: -3,
    padding: "0 5px",
  },
  inner: {
    maxWidth: 310,
    padding: "20px",
    color: "#777777",
    direction: ({ rtl }) => (rtl ? "rtl" : "ltr"),
    backgroundColor: "#FFFFFF",
    borderColor: "#B7B7B7",
    borderRadius: 4,
    border: "1px solid #b7b7b7",
    ...contentStyle,
  },
  arrow: {
    position: "absolute",
    width: "0",
    height: "0",
    borderColor: "transparent",
    borderStyle: "solid",
  },
  arrowTop: {
    left: "50%",
    bottom: -3,
    marginLeft: -7,
    borderWidth: "10px 7px 0",
    borderTopColor: "#FFFFFF",
    "&:after": {
      content: "' '",
      position: "absolute",
      zIndex: -1,
      width: 0,
      height: 0,
      borderColor: "transparent",
      borderStyle: "solid",
      borderWidth: "10px 7px 0",
      borderTopColor: "#B7B7B7",
      bottom: -2,
      left: -7,
    },
  },
  arrowRight: {
    top: "50%",
    left: -3,
    marginTop: -7,
    borderWidth: "7px 10px 7px 0",
    borderRightColor: "#FFFFFF",
    "&:after": {
      content: "' '",
      position: "absolute",
      zIndex: -1,
      width: 0,
      height: 0,
      borderColor: "transparent",
      borderStyle: "solid",
      borderWidth: "7px 10px 7px 0",
      borderRightColor: "#B7B7B7",
      top: -7,
      left: -2,
    },
  },
  arrowLeft: {
    top: "50%",
    right: -3,
    marginTop: -7,
    borderWidth: "7px 0 7px 10px",
    borderLeftColor: "#FFFFFF",
    "&:after": {
      content: "' '",
      position: "absolute",
      zIndex: -1,
      width: 0,
      height: 0,
      borderColor: "transparent",
      borderStyle: "solid",
      borderWidth: "7px 0 7px 10px",
      borderLeftColor: "#B7B7B7",
      top: -7,
      right: -2,
    },
  },
  arrowBottom: {
    left: "50%",
    top: -3,
    marginLeft: -7,
    borderWidth: "0 7px 10px",
    borderBottomColor: "#FFFFFF",
    "&:after": {
      content: "' '",
      position: "absolute",
      zIndex: -1,
      width: 0,
      height: 0,
      borderColor: "transparent",
      borderStyle: "solid",
      borderWidth: "0 7px 10px",
      borderBottomColor: "#B7B7B7",
      left: -7,
      top: -2,
    },
  },
  arrowOverRides: {
    ...arrowStyle,
  },
});

export default styles;
